name: Build Dev
on:
  push:
    branches: [master, main]

jobs:
  Build Docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - uses: benjlevesque/short-sha@v1.2
        name: Get short SHA
        id: short-sha
        with:
          length: 7

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: averyanalex
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            averyanalex/nnm:dev
            averyanalex/nnm:${{ steps.short-sha.outputs.sha }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
