on:
  release:
    types:
      - published

jobs:
    build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install GO
        uses: actions/setup-go@v2
      - name: Build
        run: go build -v && mv nnm nnm-linux-x64 && GOOS=windows go build -v && mv nnm.exe nnm-windows-x64.exe
      - uses: actions/upload-artifact@v2
        with:
          name: nnm-linux-x64
          path: nnm-linux-x64
      - uses: actions/upload-artifact@v2
        with:
          name: nnm-windows-x64.exe
          path: nnm-windows-x64.exe
    docker:
      runs-on: ubuntu-latest
      steps:
        - name: Set up QEMU
          uses: docker/setup-qemu-action@v1

        - uses: benjlevesque/short-sha@v1.2
          name: Get short SHA
          id: short-sha
          with:
            length: 7

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1

        - name: Login to DockerHub
          uses: docker/login-action@v1 
          with:
            username: averyanalex
            password: ${{ secrets.DOCKERHUB_TOKEN }}

        - uses: actions/download-artifact@v2
          with:
            name: nnm-linux-x64

        - name: Build and push
          id: docker_build
          uses: docker/build-push-action@v2
          with:
            push: true
            platforms: linux/amd64,linux/arm64
            # context: .
            # file: ./Dockerfile
            tags: |
              averyanalex/nnm:latest
              averyanalex/nnm:${{ steps.short-sha.outputs.sha }}
              averyanalex/nnm:${{ github.event.release.tag }}
        - name: Image digest
          run: echo ${{ steps.docker_build.outputs.digest }}:
  assets:
    needs: [build]
    name: Add assets to release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
          with:
          name: nnm-linux-x64
      - name: Build project
        run: |
          zip --junk-paths linux-x64 README.md nnm-linux-x64 base.env
      - uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: linux-x64.zip
